#!/bin/sh

echo "main.c:"
cat main.c
echo "audio_client.c:"
cat audio_client.c
echo "audio/"
echo "input.c:"
cat audio/input.c
echo "input.h:"
cat audio/input.h
echo "output.c:"
cat audio/output.c
echo "output.h:"
cat audio/output.h
echo "client/"
echo "playback.c:"
cat client/playback.c
echo "client_network.h:"
cat client/client_network.h
echo "client_network.c:"
cat client/client_network.c
echo "cmdline.c:"
cat client/cmdline.c
echo "record.h:"
cat client/record.h
echo "cmdline.h:"
cat client/cmdline.h
echo "record.c:"
cat client/record.c
echo "playback.h:"
cat client/playback.h
echo "network/"
echo "network.c:"
cat network/network.c
echo "network.h:"
cat network/network.h
echo "utils/"
echo "utils.c:"
cat utils/utils.c
echo "utils.h:"
cat utils/utils.h
echo "logging.c:"
cat utils/logging.c
echo "logging.h:"
cat utils/logging.h
